# Generated by Django 5.2.7 on 2025-10-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='questions',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='description',
            field=models.CharField(default='No description', max_length=100),
        ),
    ]
