# Generated by Django 5.2.7 on 2025-10-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_quizzes_questions_quizzes_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzes',
            old_name='title',
            new_name='name',
        ),
    ]
