# Generated by Django 5.2.7 on 2025-10-26 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_questions_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_Id',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='quiz_Id',
            new_name='quiz_id',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quizzes')),
            ],
        ),
    ]
