# Generated by Django 5.2.7 on 2025-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_answer_question_id_alter_questions_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=80),
        ),
    ]
